### ISSUE TITLE
Log In View

### ISSUE THREAD

**Issue by lienvdsteen** [cmw0513/scorecard#6]
### Phone (iPhone 6 size)
![1-login](https://cloud.githubusercontent.com/assets/1777175/10321923/a151562e-6c7b-11e5-9c21-344bebc43034.jpg)

### Web
![1-login](https://cloud.githubusercontent.com/assets/1777175/10321958/c7eb9c54-6c7b-11e5-9743-837fe4dd3353.jpg)

**Comment by lienvdsteen** [comment]
@cmw0513 here are some handwritten fonts: http://www.1001fonts.com/handwritten+google-web-fonts.html?page=1&items=10
(for the brand name and the name list)

**Comment by cmw0513** [comment]
I like this one http://www.1001fonts.com/kalam-font.html maybe even as a header font for the player page?

and maybe this one for the brand name: http://www.1001fonts.com/cabin-sketch-font.html

**Comment by cmw0513** [comment]
or http://www.1001fonts.com/permanent-marker-font.html
